### ISSUE TITLE
[Feature] Implement time speed up

### ISSUE THREAD

**Issue by EinsKatze** [martin-coding/godot-os-war#8]
(imo this has the lowest priority as of now)
Implement a Button or something similar to let the player speed up the game.
This will give experienced players the ability to finish the waves faster and finish runs faster or get faster to a more difficult part in the game.

**Comment by mathew-tran** [comment]
merged in: https://github.com/martin-coding/godot-os-war/commit/33723c2796eefa0c152c1a00e0ec62ee2f9c4219
